Periodogram now automatically removes nans from lightcurve
KeplerGO/lightkurve pull request #798
Opened 2020-08-07 08:56 UTC by ojhall94

Following a discussion had on the development of a tutorial, I've updated the `LightCurve` and `Periodogram` classes so that the check for NaN values in the light curve is now checked in the `LightCurve.to_periodogram()` function, instead of the `Periodogram.from_lightcurve()` function. If there are NaN values present when `to_periodogram()` is called, the function removes them and logs a warning informing the user of what's happening.

2020-08-07 08:59 UTC, ojhall94 commented
To be honest having played around with it a little I dont think the warning is necessary--- the removal of NaNs is just absorbed into the process.

2020-08-26 12:45 UTC, dhomeier requested changes
Overall this looks good and certainly helpful for curating input data.
But as indicated in the inline comments, I am a bit concerned that this makes too drastic modifications of the input data without any user notification. But I don't have much practical expertise; does the NaN removal pop up so frequently that even the warnings become annoying? I noted that `TimeSeries` sets NaNs quite abundantly for missing data, empty bins etc...
I think one option would be to reduce the warning level as suggested, another to add a kwarg to enable `remove_nans` (possibly even defaulting to `True`), yet another, as also sketched, keeping `LombScarglePeriodogram..from_lightcurve` as a NaN-aware method – though that different behaviour could also cause confusion. Or a combination of the three...
And I guess this deserves a Changelog entry.

2020-08-26 12:45 UTC, dhomeier commented on lightkurve/lightcurve.py
> +                            'These are removed before creating the periodogram.')
```suggestion
                log.info('Lightcurve contains NaN values.'
                            'These are removed before creating the periodogram.')
```
I would suggest not to remove the message entirely, going from previous behaviour of raising an exception to silently "correcting" the same input without any feedback to the user. See general discussion for alternatives.

2020-08-26 12:45 UTC, dhomeier commented on lightkurve/periodogram.py
> -
As the NaNs are already filtered out in the caller, there is no real need to remove the exception here. And worse, calling `LombScarglePeriodogram.from_lightcurve()` directly will now return an invalid periodogram without warning:
```
>>> pg = lk.periodogram.LombScarglePeriodogram.from_lightcurve(lc.normalize(unit='ppm'))
>>> pg.power
<Quantity [nan, nan, nan, ..., nan, nan, nan] ppm>
```

2020-08-26 12:45 UTC, dhomeier commented on lightkurve/tests/test_periodogram.py
> -
Complementary to the previous comment, I don't have a good feeling about removing a test for invalid input without substitute. One option would be (with the exception kept in place) to replace the check by
`LombScarglePeriodogram.from_lightcurve(lc_with_nans)`
but this probably needs some further discussion if we are willing to have the two methods `to_periodogram` /  `from_lightcurve` behave differently on NaN input.

2020-08-27 00:43 UTC, barentsen commented
I agree that:
* removing NaNs should probably happen in the `from_lightcurve` function so the behavior is consistent regardless of how the periodogram is created;
* I would at most use `log.debug` to log NaNs being removed -- it is not worth a noisy warning in my opinion.

2020-08-28 14:08 UTC, ojhall94 commented
Hey all,

I've made the changes proposed above & discussed in the telecon-- `from_lightcurve` makes the checks now, which is in line with the `BLSPeriodogram` class as well.

2020-08-28 21:38 UTC, barentsen commented on lightkurve/periodogram.py
> +        if (~np.isfinite(lc.flux)).any():
`remove_nans` will only remove nans, not infinite values, so I think we should do this?
```suggestion
        if np.isnan(lc.flux).any():
```

2020-08-28 21:39 UTC, barentsen commented on lightkurve/periodogram.py
> +            'These are removed before creating the periodogram.')
PEP8 indentation:
```suggestion
            log.debug('Lightcurve contains NaN values.'
                      'These are removed before creating the periodogram.')
```

2020-08-31 19:53 UTC, merged